# Generated by Django 4.2.11 on 2025-06-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subject', models.CharField(choices=[('TOAN', 'Toán'), ('LY', 'Vật Lý'), ('HOA', 'Hóa Học'), ('SINH', 'Sinh Học'), ('VAN', 'Ngữ Văn'), ('ANH', 'Tiếng Anh'), ('TIN', 'Tin Học')], max_length=10)),
                ('question_type', models.CharField(choices=[('CODE', 'Lập trình'), ('MCQ', 'Trắc nghiệm'), ('WRIT', 'Tự luận')], max_length=10)),
                ('content', models.TextField()),
                ('input_sample', models.TextField(blank=True, null=True)),
                ('output_sample', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
