# Generated by Django 3.2.25 on 2025-07-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='content',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='input_sample',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='output_sample',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='question_type',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='subject',
        ),
        migrations.AddField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Dễ'), ('medium', 'Trung bình'), ('hard', 'Khó')], default='easy', max_length=10),
        ),
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
