# Generated by Django 3.2.25 on 2025-07-03 04:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problems', '0002_auto_20250702_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='problem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='problem',
            name='question_type',
            field=models.CharField(choices=[('CODE', 'Lập trình'), ('MCQ', 'Trắc nghiệm'), ('WRIT', 'Tự luận')], default='CODE', max_length=10),
        ),
        migrations.AddField(
            model_name='problem',
            name='subject',
            field=models.CharField(choices=[('TOAN', 'Toán'), ('LY', 'Vật Lý'), ('HOA', 'Hóa Học'), ('SINH', 'Sinh Học'), ('VAN', 'Ngữ Văn'), ('ANH', 'Tiếng Anh'), ('TIN', 'Tin Học')], default='TOAN', max_length=10),
            preserve_default=False,
        ),
    ]
