# Generated by Django 3.2.25 on 2025-07-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_auto_20250703_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='grading_criteria',
            field=models.TextField(blank=True, help_text='Tiêu chí chấm bài (dành cho AI)', null=True),
        ),
    ]
