# Generated by Django 3.2.25 on 2025-07-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_problem_grading_criteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='choice_a',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='choice_b',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='choice_c',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='choice_d',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='correct_answer',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], help_text='Chỉ áp dụng cho câu hỏi trắc nghiệm', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Dễ'), ('medium', 'Trung bình'), ('hard', 'Khó')], max_length=10),
        ),
        migrations.AlterField(
            model_name='problem',
            name='question_type',
            field=models.CharField(choices=[('CODE', 'Lập trình'), ('MCQ', 'Trắc nghiệm'), ('WRIT', 'Tự luận')], default='WRIT', max_length=10),
        ),
    ]
