# Generated by Django 3.2.25 on 2025-09-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_alter_problem_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
