# Generated by Django 3.2.25 on 2025-07-10 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='created_at',
        ),
        migrations.AddField(
            model_name='exam',
            name='end_time',
            field=models.DateTimeField(default='2025-07-01 12:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='start_time',
            field=models.DateTimeField(default='2025-07-01 12:00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exam',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
