# Generated by Django 3.2.25 on 2025-07-11 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_examchoice_examproblem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examproblem',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='exams.exam'),
        ),
    ]
