# Generated by Django 3.2.25 on 2025-07-19 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_alter_examproblem_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='examproblem',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='examproblem',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_problems', to='exams.exam'),
        ),
    ]
