# Generated by Django 3.2.25 on 2025-08-23 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_auto_20250719_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examproblem',
            name='order',
        ),
        migrations.AlterField(
            model_name='examproblem',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam'),
        ),
        migrations.AlterField(
            model_name='examproblem',
            name='problem_type',
            field=models.CharField(max_length=50),
        ),
    ]
