# Generated by Django 3.2.25 on 2025-08-23 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_alter_problem_difficulty'),
        ('exams', '0007_auto_20250823_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examproblem',
            name='question_text',
        ),
        migrations.AddField(
            model_name='exam',
            name='problems',
            field=models.ManyToManyField(related_name='exams', through='exams.ExamProblem', to='problems.Problem'),
        ),
        migrations.AddField(
            model_name='examproblem',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='problems.problem'),
        ),
    ]
