# Generated by Django 3.2.25 on 2025-08-23 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_auto_20250823_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examproblem',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_problems', to='exams.exam'),
        ),
    ]
