# Generated by Django 3.2.25 on 2025-08-25 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_alter_examproblem_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='examproblem',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
