# Generated by Django 3.2.25 on 2025-08-25 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0011_auto_20250825_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examproblem',
            name='choice_a',
        ),
        migrations.RemoveField(
            model_name='examproblem',
            name='choice_b',
        ),
        migrations.RemoveField(
            model_name='examproblem',
            name='choice_c',
        ),
        migrations.RemoveField(
            model_name='examproblem',
            name='choice_d',
        ),
        migrations.RemoveField(
            model_name='examproblem',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='examproblem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='examproblem',
            name='title',
        ),
    ]
