# Generated by Django 3.2.25 on 2025-09-23 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0012_auto_20250825_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exam Enrollment',
                'verbose_name_plural': 'Exam Enrollments',
                'unique_together': {('user', 'exam')},
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='enrolled_users',
            field=models.ManyToManyField(related_name='enrolled_exams', through='exams.ExamEnrollment', to=settings.AUTH_USER_MODEL),
        ),
    ]
