# Generated by Django 3.2.25 on 2025-09-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0013_auto_20250923_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='password',
            field=models.CharField(blank=True, help_text='Để trống nếu không muốn đặt mật khẩu.', max_length=128, null=True),
        ),
    ]
