# Generated by Django 3.2.25 on 2025-07-03 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='content',
            new_name='code',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='is_graded',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='score',
        ),
    ]
