# Generated by Django 3.2.25 on 2025-07-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_auto_20250703_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
